[package]
name = "file-fixer"
version = "0.1.0"
authors = ["nick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"

[dev-dependencies]
tempdir = "0.3.7"
